import Helloword from "@/components/helloword";
import User from "@/components/User";
import Head from "next/head";
export default function Home() {
  return (
    <>
      <Head>
        <title>Meu Primeiro Site em React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Olá, Mundo! Meu Primeiro site em react</h1>
      <Helloword />
      <User />
    </>
  );
}
